"""update/uninstall helpers.

The recurring hazard both of these guard against is destroying something the
user cannot get back: footage that never reached the cloud, and an rclone
remote whose token gets revoked server-side (which restoring rclone.conf will
not undo).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from dji_auto_upload import selfmanage
from dji_auto_upload.config import (
    BehaviourConfig,
    Config,
    DetectConfig,
    LoggingConfig,
    NotifierConfig,
    RemoteConfig,
    RetentionConfig,
    TelegramCredentials,
)
from dji_auto_upload.paths import AppPaths


def _cfg(paths: AppPaths) -> Config:
    return Config(
        remote=RemoteConfig(name="gdrive", path_template="DJI/{date}"),
        retention=RetentionConfig(),
        detect=DetectConfig(),
        behaviour=BehaviourConfig(),
        notifier=NotifierConfig(),
        logging=LoggingConfig(),
        telegram=TelegramCredentials(),
        paths=paths,
    )


def test_unuploaded_files_lists_only_what_is_not_ledgered(tmp_app_paths: AppPaths) -> None:
    stage = tmp_app_paths.stage_dir / "2026-07-30"
    stage.mkdir(parents=True)
    (stage / "DONE.MP4").write_bytes(b"x")
    (stage / "PENDING.MP4").write_bytes(b"x")
    (stage / ".uploaded").write_text("DONE.MP4\n", encoding="utf-8")

    assert selfmanage.unuploaded_files(_cfg(tmp_app_paths)) == ["2026-07-30/PENDING.MP4"]


def test_nothing_pending_when_everything_is_ledgered(tmp_app_paths: AppPaths) -> None:
    stage = tmp_app_paths.stage_dir / "2026-07-30"
    stage.mkdir(parents=True)
    (stage / "DONE.MP4").write_bytes(b"x")
    (stage / ".uploaded").write_text("DONE.MP4\n", encoding="utf-8")

    assert selfmanage.unuploaded_files(_cfg(tmp_app_paths)) == []


def test_update_uses_the_running_interpreter_not_a_pip_shim(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A stale pip.exe launcher can point at an interpreter that no longer
    exists, so the upgrade must go through sys.executable -m pip."""
    seen: list[list[str]] = []

    def fake_run(cmd: list[str], **kw: object) -> subprocess.CompletedProcess[str]:
        seen.append(cmd)
        return subprocess.CompletedProcess(cmd, 0, stdout="0.2.0", stderr="")

    monkeypatch.setattr(selfmanage.subprocess, "run", fake_run)
    assert selfmanage.update("SRC", reinstall_trigger=False) == 0

    assert seen[0][:4] == [sys.executable, "-m", "pip", "install"]
    assert "SRC" in seen[0]


def test_update_reports_failure_instead_of_claiming_success(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def fake_run(cmd: list[str], **kw: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(cmd, 1, stdout="", stderr="network is down")

    monkeypatch.setattr(selfmanage.subprocess, "run", fake_run)
    assert selfmanage.update("SRC", reinstall_trigger=False) == 1


def test_update_refreshes_the_trigger_in_a_fresh_process(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The running process holds the OLD templates, so the trigger has to be
    regenerated by a newly started interpreter."""
    seen: list[list[str]] = []

    def fake_run(cmd: list[str], **kw: object) -> subprocess.CompletedProcess[str]:
        seen.append(cmd)
        return subprocess.CompletedProcess(cmd, 0, stdout="0.2.0", stderr="")

    monkeypatch.setattr(selfmanage.subprocess, "run", fake_run)
    selfmanage.update("SRC", reinstall_trigger=True)

    assert any(
        c[:2] == [sys.executable, "-m"] and "install-trigger" in c and "--force" in c
        for c in seen
    ), seen


def test_pip_uninstall_command_targets_this_interpreter() -> None:
    cmd = selfmanage.pip_uninstall_command()
    assert sys.executable in cmd
    assert "uninstall -y dji-auto-upload" in cmd


def test_remove_paths_tolerates_missing_entries(tmp_path: Path) -> None:
    present = tmp_path / "gone.txt"
    present.write_text("x", encoding="utf-8")
    selfmanage.remove_paths([present, tmp_path / "never-existed"])
    assert not present.exists()


def test_update_force_reinstalls_because_branch_builds_share_a_version(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`pip install --upgrade <url>` compares 0.2.0 to 0.2.0, decides the
    requirement is satisfied, and installs NOTHING while printing a wall of
    "Requirement already satisfied" that reads like success. The package must
    be forced in, or every update after the first is a silent no-op."""
    seen: list[list[str]] = []

    def fake_run(cmd: list[str], **kw: object) -> subprocess.CompletedProcess[str]:
        seen.append(cmd)
        return subprocess.CompletedProcess(cmd, 0, stdout="0.2.0", stderr="")

    monkeypatch.setattr(selfmanage.subprocess, "run", fake_run)
    selfmanage.update("SRC", reinstall_trigger=False)

    forced = [c for c in seen if "--force-reinstall" in c]
    assert forced, f"no forced reinstall issued: {seen}"
    # --no-deps keeps the force pass from needlessly rebuilding every dependency.
    assert "--no-deps" in forced[0]
